name = "StandardYoungTableaux"
uuid = "ae443f46-3c91-4a85-9741-732d995991b6"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25.65"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
